env:
  global:
    - secure: "NlWO/NTPlOU6cowOMuPOvjAprXVwIjmpHHf9CoMR71E2c/eBFFKIHj10kXuyFwz2KihHAIExmo9OlGtGniNWobvIrVrabO3dsOSb6UGbPAQkzQiyQLKsDNQAZx3nMuWEKBtMsVRee6rd7/2uGTY4WB5Ot3VhrUYcN1FoRgQQ9gk="

branches:
  only:
    - main

matrix:
  include:
    - os: linux
      dist: focal
    - os: osx
      osx_image: xcode11.5

language: cpp
compiler:
  - gcc
  - clang

script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Release -DKDBindings_TESTS=True -KDBindings_EXAMPLES=True ..
  - make
  - make test

notifications:
  email:
    recipients:
    - allen.winter@kdab.com
    on_success:  never
    on_failure: always

dist: bionic
addons:
  apt:
    update: true
  homebrew:
    update: true
